server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: lanchonete-design-patterns-api

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    com.lanchonete: DEBUG